roomie_pipeline_node:
  ros__parameters:
    use_sim_time: true

    basic:
      world_frame: world
      mapping_camera_id: head_front_left_color
      mapping_camera_frame: head_front_left_color

    topics:
      color_topic: /head_front_left_color_rgb
      depth_topic: /head_front_left_color_depth
      mask_topic: /head_front_left_color_robot_mask
      camera_info_topic: /head_front_left_color_camera_info
      tf_topic: /tf
      tf_static_topic: /tf_static
      tsdf_output_topic: /roomie/map_surface
      detection_debug_image_topic: /roomie/detections_2d_image
      raw_detections_topic: /roomie/raw_detections

    camera:
      width: 640
      height: 480
      fx: 211.2
      fy: 211.2
      cx: 291.19999872
      cy: 240.0

    input_filter:
      depth_min_m: 0.1
      depth_max_m: 10.0
      depth_scale: 0.001
      mask_robot_threshold: 0

    tsdf:
      map_backend: nvblox
      voxel_size_m: 0.03
      truncation_distance_vox: 8.0
      max_weight: 20.0
      max_integration_distance_m: 6.0
      min_visualization_weight: 1.0
      min_color_weight: 0.1
      surface_visualization_distance_vox: 1.0
      load_map: true
      map_load_path: /home/agxi/Datasets/output/jarvis_home/nvblox/color_tsdf_map_0526_1639.nvblox
      freeze_tsdf_map: true
      save_map: false
      map_save_path: /home/agxi/Datasets/output/jarvis_home/nvblox/

    detection:
      boxer_input_size: 960
      patch_rows: 60
      patch_cols: 60
      min_patch_coverage_ratio: 0.05
      max_inference_fps: 10.0
      python_backend_enabled: true
      python_executable: /home/agxi/miniconda3/envs/jarvis/bin/python
      python_worker_script: /home/agxi/RealityLab/jarvis/src/roomie/scripts/roomie_python_inference_worker.py
      boxer_repo_path: /home/agxi/RealityLab/boxer
      boxernet_ckpt_path: /home/agxi/huggingface/boxer/boxernet_hw960in4x6d768-3e37cfc4.ckpt
      inference_device: cuda
      inference_precision: auto
      text_prompts: [lvisplus]
      owl_min_confidence: 0.25
      owl_nms_iou_threshold: 0.5
      boxernet_min_confidence: 0.5
      robot_bbox_mask_overlap: 0.25
      robot_bbox_center_overlap: 0.5
      robot_mask_dilate_px: 3
      show_3d_label_score: true

    queues:
      input_queue_size: 30
      output_queue_size: 1
      sync_queue_size: 30
      pending_frame_limit: 120
      mapping_queue_size: 30
      detection_queue_size: 8
      inference_request_queue_size: 2
      inference_response_queue_size: 8

    sync:
      max_image_stamp_delta_sec: 0.002
      tf_buffer_duration_sec: 5.0
      max_tf_gap_sec: 0.2
      max_tf_translation_step_m: 0.5
      max_tf_rotation_step_deg: 45.0

    publishing:
      publish_period_sec: 5.0

    persistence:
      save_instance_map: true
      instance_map_save_path: /home/agxi/Datasets/output/jarvis_home/instances/

    logging:
      enabled: true
      root_dir: /home/agxi/RealityLab/jarvis/src/roomie/logs/roomie_runs
      period_sec: 2.0
